image: node:20-slim

stages:
  - install
  - lint
  - format
  - build
  - security_scan
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

lint:
  stage: lint
  script:
    - npm run lint

format:
  stage: format
  script:
    - npm run format-test

type-check:
  stage: build
  script:
    - npm run type-check
    - npm run build

include:
  - template: SAST.gitlab-ci.yml

deploy:
  stage: deploy
  image: docker:latest
  tags:
    - dind
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_IMAGE_NAME: $CI_REGISTRY_USER/idatt2106_2024_02_frontend-app
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username $CI_REGISTRY_USER --password-stdin
    - docker build -t $DOCKER_IMAGE_NAME:production .
    - docker push $DOCKER_IMAGE_NAME:production
  only:
    - production
