stages:
  - setup
  - lint_and_format
  - build
  - test

default:
  image: node:20

before_script:
  - npm install

format-code:
  stage: lint_and_format
  script:
    - npm run format

lint-code:
  stage: lint_and_format
  script:
    - npm run lint

build-and-test:
  stage: build
  script:
    - npm run type-check
    - npm run build

unit-tests:
  stage: test
  script:
    - npm run test:unit

e2e-tests:
  stage: test
  script:
    - npm run test:e2e

test-coverage:
  stage: test
  script:
    - npm run test:coverage
