stages:
  - setup
  - lint_and_format
  - build
  - test
  - security_scan

default:
  image: node:20

before_script:
  - npm install

format-code:
  stage: lint_and_format
  script:
    - npm run format

lint-code:
  stage: lint_and_format
  script:
    - npm run lint

build-and-test:
  stage: build
  script:
    - npm run type-check
    - npm run build

unit-tests:
  stage: test
  script:
    - npm run test:unit

test:e2e:
  image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
  stage: test:e2e
  script:
    - npm install cypress
    - npm run test:e2e

test-coverage:
  stage: test
  script:
    - npm run test:coverage

include:
  - template: SAST.gitlab-ci.yml

sast:
  stage: security_scan
  script:
    - echo "Running SAST..."
